// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    'getting-started',
    {type: 'autogenerated', dirName: 'lab-01-discover-cbom-qse'},
    {type: 'autogenerated', dirName: 'lab-02-analysis-policy-migration'},
    {type: 'autogenerated', dirName: 'lab-03-adaptive-remediation-qsr'},
  ],
  resourcesSidebar: [
    {type: 'autogenerated', dirName: 'resources'},
  ],
};

export default sidebars;
