// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    'getting-started',
    {
      type: 'category',
      label: 'Lab 1: Discover and Inventory CBOM',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'lab-01-discover-cbom-qse/index',
          label: 'Overview',
        },
        'lab-01-discover-cbom-qse/environment-setup',
      ],
    },
    {
      type: 'category',
      label: 'Lab 2: Analysis, Policy & Migration',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'lab-02-analysis-policy-migration/index',
          label: 'Overview',
        },
        'lab-02-analysis-policy-migration/environment-setup',
      ],
    },
    {
      type: 'category',
      label: 'Lab 3: Adaptive Remediation',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'lab-03-adaptive-remediation-qsr/index',
          label: 'Overview',
        },
        'lab-03-adaptive-remediation-qsr/environment-setup',
      ],
    },
  ],
  resourcesSidebar: [
    {type: 'autogenerated', dirName: 'resources'},
  ],
};

export default sidebars;
