// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    'getting-started',
    {
      type: 'category',
      label: 'Lab 1A: Introduction to IBM Defense Model with ARGUS AI',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'lab-01a-intro-defense-model/index',
          label: 'Overview',
        },
      ],
    },
    {
      type: 'category',
      label: 'Lab 1B: Unstructured Data Processing',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'lab-01b-unstructured-data/index',
          label: 'Overview',
        },
      ],
    },
    {
      type: 'category',
      label: 'Lab 2: IBM Defense Model Factchecker',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'lab-02-factchecker/index',
          label: 'Overview',
        },
      ],
    },
    {
      type: 'category',
      label: 'Lab 3: Fine Tuning with IBM Defense Model',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'lab-03-fine-tuning/index',
          label: 'Overview',
        },
      ],
    },
  ],
  resourcesSidebar: [
    {type: 'autogenerated', dirName: 'resources'},
  ],
};

export default sidebars;

// Made with Bob
